BINARY_NAME=profiler

clean:
	rm -f output.md && rm -f output.txt && rm -f bin/*

build:
	GOOS=darwin GOARCH=arm64 go build -o bin/${BINARY_NAME}-darwin-arm64 cmd/main.go
	GOOS=linux GOARCH=amd64 go build -o bin/${BINARY_NAME}-linux-amd64 cmd/main.go

start:
	go run cmd/main.go -n 20 -r md -c 100 /Users/chistadata/sandbox/ClickBench/clickhouse-local/logs/server_2.log

run:
	bin/${BINARY_NAME}-darwin-arm64 -n 20 -r md /Users/chistadata/sandbox/ClickBench/clickhouse-local/logs/server.log

run_md:
	bin/${BINARY_NAME}-darwin-arm64 md /Users/chistadata/sandbox/ChistaDATA-Profiler-for-ClickHouse/resources/logs/clickhouse-server-2.log

test:
	go test ./...

test_cover:
	go test -cover ./...

test_cover_html:
	go test -coverprofile=resources/coverage.out ./... && go tool cover -html=resources/coverage.out