%undefine _missing_build_ids_terminate_build
%global debug_package %{nil}

Summary: ChistaDATA Anansi is a log analysing tool built for ClickHouse. It is a CLI tool written in pure GO. The reports generated by the profiler sheds light on the different aspects of queries like execution time, memory usage, bytes read and other basic but crucial information. 

Name: anansi-profiler
Version: 0.0.1
Release: 1
License: GPLv3
SOURCE0: anansi-profiler.tar.gz

BuildRequires: git, make

%description
ChistaDATA Anansi is a log analysing tool built for ClickHouse.


%prep
%setup -n anansi-profiler

%build
make build

%install
install -d %{buildroot}/%{_bindir}
install -D -m 0755 %{_builddir}/%name/anansi-profiler %{buildroot}/%{_bindir}

%files
%doc README.md
%{_bindir}/anansi-profiler

%changelog
* Fri Feb 10 2023 John Doe <john.doe@example.com> - 0.0.1-1
- Initial release